### ISSUE TITLE
Key exchange not working, encrypted messages unreadable

### ISSUE THREAD

**Issue by madduck** [matrix-org/olm#84]
In multiple situations, we've come up against the problem wherein keys are no longer properly exchanged and/or synchronised, resulting in what seems to be persistent inability of certain parties to communicate with each other. This happens across clients (Android, iOS, Web), and while it seems to only affect a subset of people, a pattern is not discernable to my eyes.

I am creating this issue with the plan to create rageshake pairs, mentioning this issue, in the hope that this will help exposing the underlying bug, such that it can be fixed without having to wait for the e2e rewrite.

What is curious is that the issue seems to be between two accounts, not dependent on any room. Take this case, in which the two parties (my cousin and I) couldn't continue using the DM room they had going for years (due to aforementioned e2e issue), and we thus created a new room. You can see a screenshot of the old room shared in the new room:

![image](https://github.com/matrix-org/olm/assets/195073/dc9fb480-b195-4d33-8e12-b169fd223ecb)

Right away, we were unable to communicate with each other.

There's another room with all the other siblings and cousins, wherein her messages, as well as mine, are not decipherable by anyone, but the others are able to communicate fine:

![image](https://github.com/matrix-org/olm/assets/195073/7dadac1c-2727-4f42-aa58-15c878722af4)

I'll now try to get pairwise rageshakes, mentioning this issue.

**Comment by madduck** [comment]
A rageshake pair has just been submitted, concerning users "martin" and "Andy" in the above. Both Android. Both submitted in the last 60 seconds.

**Comment by richvdh** [comment]
> What is curious is that the issue seems to be between two accounts, not dependent on any room. 

This is not unusual. Most failures in the e2e system happen at the device level rather than the room level: they involve one device not knowing about another, or key-share messages (which happen outside a room) getting lost.

---

I struggled to correlate the screenshots to the rageshakes, but eventually I found a pair for the 20:12 event (event id `$iNowTQdD-jrnRoQ_DxX6wFbn9oWgX2B6P-sy2lHf1MM`, for the record).

From that event, on the sender side, I see:

```
2023-05-27T18:12:47*161GMT+00:00Z 1116 D/ /CRYPTO/MXMegolmEncryption: notifyKeyWithHeld() :sending withheld for session:0hMkbm1UvlkckE9TpdxbwpsMEYp1ZhQSwDr1VZincrM and code UNVERIFIED to ... <recipient device>.
```

It looks like you might have enabled "Encrypt to verified sessions only" (under the "Security & Privacy" settings)? If so: (1) was that deliberate, (2) have you attempted to verify the other users in the room, (3) have all those other users made sure that their devices are verified?

This also explains the slightly different error ("Du kannst auf diese Nachricht nicht zugreifen" rather than "Warte auf diese Nachricht") for that event.

---

The messages from "bebeas" seem to have a different problem, but I'll need a rageshake from that device to investigate further.

**Comment by richvdh** [comment]
(btw we normally track this sort of issue on one of the `vector-im/element-{web,android,ios,meta}` repositories, but we're here now and github won't let me transfer the issue to the other organisation)

**Comment by madduck** [comment]
Hi @richvdh, I am sorry for filing in the wrong place. Thanks for letting me get by this time.

So the "encrypt to verified sessions only" setting was indeed on for the Android client, but it's not enabled for the Web client. I am also *fairly* sure that I didn't enable this by hand. It's been a journey to get people to use Element/Matrix, so no, I didn't actually think about device verification yet.

Anyway, I've now disabled the setting, and lo-and-behold, it now works fine. Good to know.

May I ask: is the reason you asked me whether I deliberately enabled the setting that it can turn itself on without my doing?

**Comment by richvdh** [comment]
>  but it's not enabled for the Web client.

Ok, if you have examples of events sent from the Web client that others cannot decrypt, please, once again, send rageshakes from both sides. By the way, it's really helpful for looking through the logs if you can mention the event id of a problematic event.

> May I ask: is the reason you asked me whether I deliberately enabled the setting that it can turn itself on without my doing?

Not to my knowledge! If it did, that would be a bug to raise against `element-android`... but to be honest, unless there are other similar reports, I think it's more likely you turned it on somehow.

**Comment by richvdh** [comment]
I'm going to close this as the reported install appears to have been due to user settings.

**Comment by madduck** [comment]
Good work @richvdh, I'll create another issue for the second problem once I can link up with the user in person.
